### ISSUE TITLE
Transition not working

### ISSUE THREAD

**Issue by nickbutcher** [TheShapGuy/CustomTransition#1]
Hi, i've not built the code but reading the transition I can see your issue; you need to manually set the `X`, `Y` and `Z` position of the views (just like you're manually setting the scale + alpha values of the actions). 

As you're running the animation sequentially, the view's X/Y position is not set to `startX` & `startY` until the animation starts. That's why you're seeing it briefly in it's layout position (at the top) while the action anims run, then it jumps to `startX`, `startY` and animates back into place.

Out of interest, why not just use a `ChangeBounds` transition to handle the move and run enter transitions on the actions?

**Comment by TheShapGuy** [comment]
Thanks! Fixed!

I'm just trying out understand the ins and outs of transitions therefore not using ChangeBounds.
